name: Update documentation
on:
  workflow_dispatch:
jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Repositories.md
        run: |
            echo "|Repository|Description|Info|Last Updated|" > docs/Repositories.md
            echo "|---|---|---|---|" >> docs/Repositories.md
            gh repo list WIFORCE | sed "s:\t:|:g" | sed 's:$:|:' | sed 's:^:|:' | grep -v .github | sort >> docs/Repositories.md
        env:
          GH_TOKEN: ${{ secrets.WIFORCE_ACTION }}
      - name: Merge into README
        run: |
            echo "
            ## Repositories
            " > tmp.md
            cat docs/Introduction.md tmp.md docs/Repositories.md > profile/README.md
            rm tmp.md
      - name: Commit and push changes
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/Repositories.md profile/README.md
            git commit -m "Updated the documentation with the latest repositories"
            git push
    
# Note: It is possible to use a more sophisticated `gh` command to get the list of repositories.
# ```bash
# gh repo list --json name,description,isPrivate,isFork,isArchived --template \
# '{{range .}}{{tablerow (printf "|%s|%s|%s|" .name .description .isPrivate)}}{{end}}'
# ``` using the `--json` and `--template` options (written in Go template syntax) to format 
# the output directly as a Markdown table. However, the current implementation using `sed` 
# and `grep` is simpler and sufficient for our needs.
