name: Update documentation
on:
  workflow_dispatch:
jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Repositories.md
        run: 
            echo "|Repository|Description|Info|Last Updated|\n|---|------|---|---|" > docs/Repositories.md
            gh repo list WIFORCE | sed "s:\t:|:g" | sed 's:$:|:' | sed 's:^:|:' | grep -v .github | sort >> docs/Repositories.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge into README
        run: |
            cat docs/Introduction.md "\n## Repositories\n" docs/Repositories.md > profile/README.md
      - name: Commit and push changes
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/Repositories.md profile/README.md
            git commit -m "Updated the documentation with the latest repositories"
            git push
    
